### ISSUE TITLE
Everytime trying to install it, it break the app

### ISSUE THREAD

**Issue by francois2sap** [juhamust/mozaik-ext-image#3]
Hello! 
I have the v1 of mozaik-demo, I tried to install this widget on my app, but it broke everything on it, I had the Calendar working perfectly, and now whenever I remove the few lines where I registered this extension, it does not work :((
I also tried with a brand new installation of Mozaik 1, but same issue.
```warning package.json: "dependencies" has dependency "babel-register" with range "6.7.2" that collides with a dependency in "devDependencies" of the same name with version "^6.7.2"
warning mozaik-dashboard@0.2.0: "dependencies" has dependency "babel-register" with range "6.7.2" that collides with a dependency in "devDependencies" of the same name with version "^6.7.2"
[1/5] Validating package.json...
warning mozaik-dashboard@0.2.0: "dependencies" has dependency "babel-register" with range "6.7.2" that collides with a dependency in "devDependencies" of the same name with version "^6.7.2"
[2/5] Resolving packages...
success Already up-to-date.
$ if $BUILD_ASSETS; then npm run build-assets; fi

> mozaik-dashboard@0.2.0 build-assets /home/fdesaporta/Documents/mozaik-demo
> gulp build

[11:43:26] Using gulpfile ~/Documents/mozaik-demo/gulpfile.js
[11:43:26] Starting 'copy:fonts'...
[11:43:26] Copying fonts
[11:43:26] Starting 'copy:styles'...
[11:43:26] Copying styles
[11:43:26] Starting 'copy:imgs'...
[11:43:26] Copying images from extensions and themes
[11:43:26] Starting 'collect:styles'...
[11:43:26] Collecting extensions styles
[11:43:26] Finished 'collect:styles' after 6.66 ms
[11:43:26] Starting 'styles:dev'...
[11:43:26] Compiling stylus code using theme '/home/fdesaporta/Documents/mozaik-demo/node_modules/mozaik/src/themes/night-blue'
[11:43:26] Starting 'js'...
[11:43:26] Finished 'styles:dev' after 50 ms
[11:43:26] Starting 'styles'...
[11:43:26] Finished 'styles' after 30 μs
[11:43:26] Finished 'copy:imgs' after 61 ms
[11:43:26] Finished 'copy:styles' after 235 ms
[11:43:26] Finished 'copy:fonts' after 412 ms
[11:43:26] Starting 'copy'...
[11:43:26] Finished 'copy' after 2.01 μs
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'mozaik-ext-calendar' from '/home/fdesaporta/Documents/mozaik-demo/src'
    at /home/fdesaporta/Documents/mozaik-demo/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/fdesaporta/Documents/mozaik-demo/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/fdesaporta/Documents/mozaik-demo/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/fdesaporta/Documents/mozaik-demo/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/fdesaporta/Documents/mozaik-demo/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/fdesaporta/Documents/mozaik-demo/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)

npm ERR! Linux 4.18.0-16-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build-assets"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! mozaik-dashboard@0.2.0 build-assets: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mozaik-dashboard@0.2.0 build-assets script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mozaik-dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mozaik-dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mozaik-dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fdesaporta/Documents/mozaik-demo/npm-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command. 
```

All help is appreciated!! Thanks for reading, I can add every errors/files you need :)

**Comment by durzo** [comment]
Same here, fixed it by doing:
`rm -rf node_modules/mozaik-ext-image && npm i -S mozaik-ext-image@0.4.0`
